# Generated by Django 4.0.4 on 2022-06-12 17:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_alter_dislike_user_alter_like_user_alter_post_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='enrolled',
            field=models.ManyToManyField(blank=True, default=None, related_name='enrolled', to=settings.AUTH_USER_MODEL),
        ),
    ]
