# Generated by Django 4.0.4 on 2022-06-12 18:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0004_post_enrolled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='enrolled',
            field=models.ManyToManyField(blank=True, related_name='enrolled', to=settings.AUTH_USER_MODEL),
        ),
    ]
