# Generated by Django 4.0.4 on 2022-06-26 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_userenrolled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userenrolled',
            name='value',
            field=models.CharField(choices=[('enroll', 'enroll'), ('unenroll', 'unenroll')], default='enrolled', max_length=20),
        ),
    ]
