# Generated by Django 4.0.4 on 2022-06-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_userenrolled_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Goal',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
