# Generated by Django 4.0.4 on 2022-06-29 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_post_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='post_reply', to='base.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Description',
            field=models.TextField(blank=True, max_length=650, null=True),
        ),
    ]
