# Generated by Django 4.0.4 on 2022-07-13 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_message_notes_alter_test_message_body_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='notes',
            new_name='Notes',
        ),
    ]
