# Generated by Django 4.0.4 on 2022-07-13 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_rename_notes_test_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='Notes',
            new_name='notes',
        ),
    ]
