# Generated by Django 4.0.4 on 2022-07-13 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_rename_notes_test_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_message',
            name='notes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Test_messages', to='base.notes'),
        ),
        migrations.AlterField(
            model_name='test',
            name='notes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Test_notes', to='base.notes'),
        ),
    ]
