# Generated by Django 4.0.4 on 2022-07-16 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_test_message_notes_alter_test_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_message',
            name='notes',
        ),
    ]
