# Generated by Django 4.0.4 on 2022-07-19 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_discussionforum_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussionforum',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum_messages', to='base.post'),
        ),
    ]
